python3-pydantic-core: upgrade 2.16.3 -> 2.18.1
The currently available python-3-pydantic v2.7.0 requires
python3-pydantic-core to be updated to v2.18.1.

Removed patch: 0001-Bumps-pyo3-https-github.com-pyo3-pyo3-from-0.20.2-to:
 The pyo3 version bump patch is dropped as the pyo3 version in
 python3-pydantic-core was updated to a newer one.

Added patch: 0001-Lower-MSRV-to-1.75-1316:
 This patch for lowering the MSRV to 1.75 (from 1.76) is backported to
 fix the build (as scarthgap provides rust 1.75).

Added patch: 0001-Fix-generate_self_schema-for-Python-3.12-1299:
 This patch fixes following build error for python 3.12+ (which we have):
 TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'

Updated crate dependencies:
 ahash: 0.8.7 -> 0.8.10
 enum_dispatch: 0.3.12 -> 0.3.13
 indexmap: 2.0.0 -> 2.2.2
 jiter: 0.0.6 -> 0.2.1
 pyo3: 0.20.3 -> 0.21.1
 regex: 1.10.2 -> 1.10.3
 regex-automata: 0.4.3 -> 0.4.5
 serde: 1.0.195 -> 1.0.197
 serde_derive: 1.0.195 -> 1.0.197
 serde_json: 1.0.109 -> 1.0.114
 smallvec: 1.11.2 -> 1.13.2
 speedate: 0.13.0 -> 0.14.0
 uuid: 1.6.1 -> 1.7.0

Added new crate dependencies:
 strum_macros: 0.26.1

Removed crate dependencies:
 allocator-api2
 lexical-core
 lexical-write-float
 lexical-write-integer

Changelog:
 https://github.com/pydantic/pydantic-core/releases

Signed-off-by: Richard Leitner <dev@g0hl1n.net>